version: "3.9"

# Định nghĩa một mạng riêng cho service này
networks:
  products-net:
    driver: bridge

volumes:
  products-pg-data: # Đặt tên volume rõ ràng hơn

services:
  # 1. Service cho CSDL PostgreSQL
  products-db:
    image: postgres:15-alpine
    container_name: products-db
    networks:
      - products-net
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - products-pg-data:/var/lib/postgresql/data
    restart: unless-stopped 
    # Kiểm tra xem CSDL đã sẵn sàng nhận kết nối chưa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d products_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Service cho ứng dụng Spring Boot
  products-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: products-app
    networks:
      - products-net
    ports:
      - "8081:8081" # Cổng 8001 (host) -> 8001 (container)
    environment:
      # Ghi đè cấu hình CSDL để trỏ vào tên service "products-db"
      DB_URL: jdbc:postgresql://products-db:5432/products_db
      DB_USER: admin
      DB_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      products-db: # <-- THAY ĐỔI QUAN TRỌNG
        condition: service_healthy # Chỉ khởi động app khi CSDL "khỏe mạnh"
    restart: on-failure