apiVersion: v1
kind: Service
metadata:
  # Tên Service khớp quy tắc fullname (release + chart)
  name: {{ include "products.fullname" . }}
  labels:
    # Bộ nhãn chuẩn (chart/version/instance/component…)
    {{- include "products.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    # Annotation dành riêng cho Service (tuỳ chọn từ values.yaml)
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # Kiểu Service: ClusterIP (mặc định). Có thể đổi sang NodePort/LoadBalancer trong values.yaml
  type: {{ .Values.service.type }}

  # Cấu hình cổng Service. TargetPort dùng tên "http" (đã đặt trong Deployment)
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP

  # Selector: bắt cặp chính xác với Pod do Deployment tạo (dùng selectorLabels)
  selector:
    {{- include "products.selectorLabels" . | nindent 4 }}

  {{- /* Tuỳ chọn nâng cao cho Networking (bật qua values nếu cần) */ -}}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
